development:
  access_key_id: AKIAIMQYMOHZCIBUA67Q
  secret_access_key: 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

test:
  access_key_id: AKIAIMQYMOHZCIBUA67Q
  secret_access_key: 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

production:
  access_key_id: AKIAIMQYMOHZCIBUA67Q
  secret_access_key: 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
