# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20110619154740) do

  create_table "college_lists", :force => true do |t|
    t.string   "name_en"
    t.string   "name_cn"
    t.string   "address"
    t.string   "website"
    t.string   "school_type"
    t.string   "founded"
    t.string   "total_student"
    t.string   "enrollment"
    t.string   "acceptance_rate"
    t.string   "teacher_student_ratio"
    t.text     "student_info"
    t.text     "faculty_info"
    t.string   "sat_score"
    t.text     "ranking"
    t.text     "tuition_fee"
    t.text     "financial_aid"
    t.text     "about_school"
    t.string   "academic_calendar"
    t.text     "popular_major"
    t.text     "special_feature"
    t.text     "degree"
    t.text     "contact_info"
    t.string   "setting"
    t.string   "pics"
    t.text     "application_deadline"
    t.string   "application_fee"
    t.string   "application_method"
    t.string   "application_form"
    t.text     "application_material"
    t.text     "application_mustknow"
    t.string   "double_admission"
    t.text     "lang_requirement"
    t.text     "d_lang_requirement"
    t.string   "recommendation_form"
    t.string   "financial_form"
    t.text     "admission_requirement"
    t.string   "mail_test_score"
    t.string   "airport_help"
    t.string   "boarding"
    t.text     "notice"
    t.text     "remark"
    t.string   "status"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "highest_degree"
    t.string   "college_pic_1_file_name"
    t.string   "college_pic_1_content_type"
    t.integer  "college_pic_1_file_size"
    t.datetime "college_pic_1_updated_at"
    t.string   "college_pic_2_file_name"
    t.string   "college_pic_2_content_type"
    t.integer  "college_pic_2_file_size"
    t.datetime "college_pic_2_updated_at"
  end

  create_table "college_rankings", :force => true do |t|
    t.string   "school_type"
    t.integer  "rank"
    t.string   "name_en"
    t.string   "name_cn"
    t.string   "tuition"
    t.string   "enrollment"
    t.string   "acceptance_rate"
    t.string   "retention_rate"
    t.string   "graduation_rate"
    t.string   "class_size"
    t.string   "sat_act"
    t.integer  "college_list_id"
    t.string   "status"
    t.string   "year"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "graduate_school_rankings", :force => true do |t|
    t.string   "category"
    t.integer  "rank"
    t.string   "name_en"
    t.string   "name_cn"
    t.string   "tuition"
    t.string   "enrollment"
    t.string   "gpa"
    t.string   "gmat"
    t.string   "acceptance_rate"
    t.string   "salary"
    t.string   "graduation_rate"
    t.integer  "college_list_id"
    t.string   "status"
    t.string   "year"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "high_school_lists", :force => true do |t|
    t.string   "name_en"
    t.string   "name_cn"
    t.string   "hs_type"
    t.string   "address"
    t.string   "state"
    t.string   "zip"
    t.string   "website"
    t.text     "about_en"
    t.text     "about_cn"
    t.string   "school_pics"
    t.string   "founded"
    t.string   "grade_en"
    t.string   "grade_cn"
    t.string   "student_type_en"
    t.string   "student_type_cn"
    t.string   "religion_en"
    t.string   "religion_cn"
    t.string   "total_student"
    t.string   "total_teacher"
    t.string   "teacher_student_ratio"
    t.string   "percentage_of_asia_student"
    t.string   "num_of_chinese_student"
    t.string   "num_of_ap_class"
    t.string   "num_of_honor_class"
    t.string   "esl_class"
    t.string   "school_bus"
    t.string   "winter_entry_en"
    t.string   "winter_entry_cn"
    t.string   "fall_entry_en"
    t.string   "fall_entry_cn"
    t.string   "airport_en"
    t.string   "airport_cn"
    t.string   "uniform"
    t.string   "interview"
    t.string   "required_test"
    t.string   "avg_sac_atc"
    t.string   "tuition"
    t.string   "other_fee_en"
    t.string   "other_fee_cn"
    t.text     "facility_en"
    t.text     "facility_cn"
    t.text     "top_university"
    t.text     "club_activity_en"
    t.text     "club_activity_cn"
    t.string   "city_nearby_en"
    t.string   "city_nearby_cn"
    t.text     "about_neary_city_en"
    t.text     "about_nearby_city_cn"
    t.string   "nearby_city_pics"
    t.string   "school_level"
    t.text     "remarks"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "contact"
    t.string   "high_school_pic_file_name"
    t.string   "high_school_pic_content_type"
    t.integer  "high_school_pic_file_size"
    t.datetime "high_school_pic_updated_at"
    t.string   "high_school_city_pic_file_name"
    t.string   "high_school_city_pic_content_type"
    t.integer  "high_school_city_pic_file_size"
    t.datetime "high_school_city_pic_updated_at"
  end

  create_table "highschool_rankings", :force => true do |t|
    t.string   "year"
    t.string   "name_en"
    t.string   "name_cn"
    t.string   "address"
    t.string   "phone"
    t.string   "url"
    t.string   "usnews_link"
    t.string   "comments"
    t.string   "status"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "rank"
  end

  create_table "host_family_infos", :force => true do |t|
    t.string   "f_nm"
    t.string   "l_nm"
    t.string   "sex"
    t.date     "dob"
    t.string   "street"
    t.string   "city"
    t.string   "state"
    t.string   "zip"
    t.string   "homephone"
    t.string   "cellphone"
    t.string   "email"
    t.string   "ethnicity"
    t.string   "legal_status"
    t.string   "education"
    t.string   "religion"
    t.string   "occupation"
    t.string   "english_level"
    t.string   "primary_language"
    t.string   "second_language"
    t.string   "homestay_experience"
    t.string   "student_sex"
    t.string   "student_group"
    t.string   "marrital_status"
    t.string   "s_f_nm"
    t.string   "s_l_nm"
    t.string   "s_sex"
    t.date     "s_dob"
    t.string   "s_ethnicity"
    t.string   "s_legal_status"
    t.string   "s_education"
    t.string   "s_final_school"
    t.string   "final_school"
    t.string   "s_religion"
    t.string   "s_occupation"
    t.string   "s_english_level"
    t.string   "s_primary_language"
    t.string   "s_second_language"
    t.string   "number_of_kids"
    t.text     "kids_detail"
    t.string   "house_ownership"
    t.string   "house_type"
    t.string   "num_of_bedroom"
    t.string   "num_of_bathroom"
    t.string   "num_of_car"
    t.string   "num_of_pet"
    t.text     "pet_detail"
    t.string   "avail_room"
    t.string   "ride_avail"
    t.text     "comment"
    t.string   "way_to_know_nh"
    t.string   "ind_confirm"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "status"
    t.string   "s_live_in"
  end

  create_table "host_family_photos", :force => true do |t|
    t.integer  "host_family_info_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "host_family_pic_file_name"
    t.string   "host_family_pic_content_type"
    t.integer  "host_family_pic_file_size"
    t.datetime "host_family_pic_updated_at"
  end

  create_table "locations", :force => true do |t|
    t.string   "name"
    t.string   "address"
    t.float    "longitude"
    t.float    "latitude"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "microposts", :force => true do |t|
    t.string   "title"
    t.text     "content"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "newhope_teams", :force => true do |t|
    t.string   "name_en"
    t.string   "name_cn"
    t.string   "title_en"
    t.string   "title_cn"
    t.string   "email"
    t.string   "phone"
    t.string   "record_type"
    t.string   "branch_name_en"
    t.string   "branch_name_cn"
    t.string   "country_en"
    t.string   "country_cn"
    t.string   "pic"
    t.text     "resume"
    t.integer  "sort_order"
    t.string   "status"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "nhteampic_file_name"
    t.string   "nhteampic_content_type"
    t.integer  "nhteampic_file_size"
    t.datetime "nhteampic_updated_at"
    t.string   "newhope_team_pic_file_name"
    t.string   "newhope_team_pic_content_type"
    t.integer  "newhope_team_pic_file_size"
    t.datetime "newhope_team_pic_updated_at"
  end

  create_table "news_updates", :force => true do |t|
    t.string   "title_en"
    t.string   "title_cn"
    t.string   "news_type"
    t.text     "context"
    t.string   "status"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "relationships", :force => true do |t|
    t.integer  "follower_id"
    t.integer  "followed_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "service_grades", :force => true do |t|
    t.string   "grade"
    t.string   "en_label"
    t.string   "cn_label"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "service_requests", :force => true do |t|
    t.string   "student_name"
    t.string   "year_of_birth"
    t.string   "gender"
    t.string   "parent_name"
    t.string   "relationship"
    t.string   "street"
    t.string   "city"
    t.string   "country"
    t.string   "nationality"
    t.string   "cell_phone"
    t.string   "home_phone"
    t.string   "email"
    t.string   "service_grade"
    t.string   "service_type"
    t.string   "service_city"
    t.string   "service_state"
    t.text     "service_detail"
    t.string   "way_to_know_nh"
    t.text     "comments"
    t.string   "status"
    t.integer  "updated_by"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "student_hostfamily_pictures", :force => true do |t|
    t.string   "student_info"
    t.string   "family_info"
    t.string   "location"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "pic_file_name"
    t.string   "pic_content_type"
    t.integer  "pic_file_size"
    t.datetime "pic_updated_at"
  end

  create_table "success_cases", :force => true do |t|
    t.string   "student_name"
    t.string   "school_name"
    t.string   "school_type"
    t.string   "pics"
    t.string   "status"
    t.integer  "user_id"
    t.text     "msg"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "record_type"
    t.string   "success_case_pic_file_name"
    t.string   "success_case_pic_content_type"
    t.integer  "success_case_pic_file_size"
    t.datetime "success_case_pic_updated_at"
  end

  create_table "translations", :force => true do |t|
    t.string   "nm"
    t.string   "controller_nm"
    t.string   "model_nm"
    t.string   "action_nm"
    t.string   "func"
    t.text     "zw_txt"
    t.text     "zw2_txt"
    t.text     "en_txt"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", :force => true do |t|
    t.string   "name"
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "encrypted_password"
    t.string   "salt"
    t.integer  "user_type_id",       :default => 3
    t.string   "cellphone"
    t.string   "homephone"
    t.string   "status"
  end

end
