require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe GraduateSchoolRankingsController do

  def mock_graduate_school_ranking(stubs={})
    @mock_graduate_school_ranking ||= mock_model(GraduateSchoolRanking, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all graduate_school_rankings as @graduate_school_rankings" do
      GraduateSchoolRanking.stub(:all) { [mock_graduate_school_ranking] }
      get :index
      assigns(:graduate_school_rankings).should eq([mock_graduate_school_ranking])
    end
  end

  describe "GET show" do
    it "assigns the requested graduate_school_ranking as @graduate_school_ranking" do
      GraduateSchoolRanking.stub(:find).with("37") { mock_graduate_school_ranking }
      get :show, :id => "37"
      assigns(:graduate_school_ranking).should be(mock_graduate_school_ranking)
    end
  end

  describe "GET new" do
    it "assigns a new graduate_school_ranking as @graduate_school_ranking" do
      GraduateSchoolRanking.stub(:new) { mock_graduate_school_ranking }
      get :new
      assigns(:graduate_school_ranking).should be(mock_graduate_school_ranking)
    end
  end

  describe "GET edit" do
    it "assigns the requested graduate_school_ranking as @graduate_school_ranking" do
      GraduateSchoolRanking.stub(:find).with("37") { mock_graduate_school_ranking }
      get :edit, :id => "37"
      assigns(:graduate_school_ranking).should be(mock_graduate_school_ranking)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created graduate_school_ranking as @graduate_school_ranking" do
        GraduateSchoolRanking.stub(:new).with({'these' => 'params'}) { mock_graduate_school_ranking(:save => true) }
        post :create, :graduate_school_ranking => {'these' => 'params'}
        assigns(:graduate_school_ranking).should be(mock_graduate_school_ranking)
      end

      it "redirects to the created graduate_school_ranking" do
        GraduateSchoolRanking.stub(:new) { mock_graduate_school_ranking(:save => true) }
        post :create, :graduate_school_ranking => {}
        response.should redirect_to(graduate_school_ranking_url(mock_graduate_school_ranking))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved graduate_school_ranking as @graduate_school_ranking" do
        GraduateSchoolRanking.stub(:new).with({'these' => 'params'}) { mock_graduate_school_ranking(:save => false) }
        post :create, :graduate_school_ranking => {'these' => 'params'}
        assigns(:graduate_school_ranking).should be(mock_graduate_school_ranking)
      end

      it "re-renders the 'new' template" do
        GraduateSchoolRanking.stub(:new) { mock_graduate_school_ranking(:save => false) }
        post :create, :graduate_school_ranking => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested graduate_school_ranking" do
        GraduateSchoolRanking.stub(:find).with("37") { mock_graduate_school_ranking }
        mock_graduate_school_ranking.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :graduate_school_ranking => {'these' => 'params'}
      end

      it "assigns the requested graduate_school_ranking as @graduate_school_ranking" do
        GraduateSchoolRanking.stub(:find) { mock_graduate_school_ranking(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:graduate_school_ranking).should be(mock_graduate_school_ranking)
      end

      it "redirects to the graduate_school_ranking" do
        GraduateSchoolRanking.stub(:find) { mock_graduate_school_ranking(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(graduate_school_ranking_url(mock_graduate_school_ranking))
      end
    end

    describe "with invalid params" do
      it "assigns the graduate_school_ranking as @graduate_school_ranking" do
        GraduateSchoolRanking.stub(:find) { mock_graduate_school_ranking(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:graduate_school_ranking).should be(mock_graduate_school_ranking)
      end

      it "re-renders the 'edit' template" do
        GraduateSchoolRanking.stub(:find) { mock_graduate_school_ranking(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested graduate_school_ranking" do
      GraduateSchoolRanking.stub(:find).with("37") { mock_graduate_school_ranking }
      mock_graduate_school_ranking.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the graduate_school_rankings list" do
      GraduateSchoolRanking.stub(:find) { mock_graduate_school_ranking }
      delete :destroy, :id => "1"
      response.should redirect_to(graduate_school_rankings_url)
    end
  end

end
