require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HighschoolRankingsController do

  def mock_highschool_ranking(stubs={})
    @mock_highschool_ranking ||= mock_model(HighschoolRanking, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all highschool_rankings as @highschool_rankings" do
      HighschoolRanking.stub(:all) { [mock_highschool_ranking] }
      get :index
      assigns(:highschool_rankings).should eq([mock_highschool_ranking])
    end
  end

  describe "GET show" do
    it "assigns the requested highschool_ranking as @highschool_ranking" do
      HighschoolRanking.stub(:find).with("37") { mock_highschool_ranking }
      get :show, :id => "37"
      assigns(:highschool_ranking).should be(mock_highschool_ranking)
    end
  end

  describe "GET new" do
    it "assigns a new highschool_ranking as @highschool_ranking" do
      HighschoolRanking.stub(:new) { mock_highschool_ranking }
      get :new
      assigns(:highschool_ranking).should be(mock_highschool_ranking)
    end
  end

  describe "GET edit" do
    it "assigns the requested highschool_ranking as @highschool_ranking" do
      HighschoolRanking.stub(:find).with("37") { mock_highschool_ranking }
      get :edit, :id => "37"
      assigns(:highschool_ranking).should be(mock_highschool_ranking)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created highschool_ranking as @highschool_ranking" do
        HighschoolRanking.stub(:new).with({'these' => 'params'}) { mock_highschool_ranking(:save => true) }
        post :create, :highschool_ranking => {'these' => 'params'}
        assigns(:highschool_ranking).should be(mock_highschool_ranking)
      end

      it "redirects to the created highschool_ranking" do
        HighschoolRanking.stub(:new) { mock_highschool_ranking(:save => true) }
        post :create, :highschool_ranking => {}
        response.should redirect_to(highschool_ranking_url(mock_highschool_ranking))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved highschool_ranking as @highschool_ranking" do
        HighschoolRanking.stub(:new).with({'these' => 'params'}) { mock_highschool_ranking(:save => false) }
        post :create, :highschool_ranking => {'these' => 'params'}
        assigns(:highschool_ranking).should be(mock_highschool_ranking)
      end

      it "re-renders the 'new' template" do
        HighschoolRanking.stub(:new) { mock_highschool_ranking(:save => false) }
        post :create, :highschool_ranking => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested highschool_ranking" do
        HighschoolRanking.stub(:find).with("37") { mock_highschool_ranking }
        mock_highschool_ranking.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :highschool_ranking => {'these' => 'params'}
      end

      it "assigns the requested highschool_ranking as @highschool_ranking" do
        HighschoolRanking.stub(:find) { mock_highschool_ranking(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:highschool_ranking).should be(mock_highschool_ranking)
      end

      it "redirects to the highschool_ranking" do
        HighschoolRanking.stub(:find) { mock_highschool_ranking(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(highschool_ranking_url(mock_highschool_ranking))
      end
    end

    describe "with invalid params" do
      it "assigns the highschool_ranking as @highschool_ranking" do
        HighschoolRanking.stub(:find) { mock_highschool_ranking(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:highschool_ranking).should be(mock_highschool_ranking)
      end

      it "re-renders the 'edit' template" do
        HighschoolRanking.stub(:find) { mock_highschool_ranking(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested highschool_ranking" do
      HighschoolRanking.stub(:find).with("37") { mock_highschool_ranking }
      mock_highschool_ranking.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the highschool_rankings list" do
      HighschoolRanking.stub(:find) { mock_highschool_ranking }
      delete :destroy, :id => "1"
      response.should redirect_to(highschool_rankings_url)
    end
  end

end
