require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HostFamilyPhotosController do

  def mock_host_family_photo(stubs={})
    @mock_host_family_photo ||= mock_model(HostFamilyPhoto, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all host_family_photos as @host_family_photos" do
      HostFamilyPhoto.stub(:all) { [mock_host_family_photo] }
      get :index
      assigns(:host_family_photos).should eq([mock_host_family_photo])
    end
  end

  describe "GET show" do
    it "assigns the requested host_family_photo as @host_family_photo" do
      HostFamilyPhoto.stub(:find).with("37") { mock_host_family_photo }
      get :show, :id => "37"
      assigns(:host_family_photo).should be(mock_host_family_photo)
    end
  end

  describe "GET new" do
    it "assigns a new host_family_photo as @host_family_photo" do
      HostFamilyPhoto.stub(:new) { mock_host_family_photo }
      get :new
      assigns(:host_family_photo).should be(mock_host_family_photo)
    end
  end

  describe "GET edit" do
    it "assigns the requested host_family_photo as @host_family_photo" do
      HostFamilyPhoto.stub(:find).with("37") { mock_host_family_photo }
      get :edit, :id => "37"
      assigns(:host_family_photo).should be(mock_host_family_photo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created host_family_photo as @host_family_photo" do
        HostFamilyPhoto.stub(:new).with({'these' => 'params'}) { mock_host_family_photo(:save => true) }
        post :create, :host_family_photo => {'these' => 'params'}
        assigns(:host_family_photo).should be(mock_host_family_photo)
      end

      it "redirects to the created host_family_photo" do
        HostFamilyPhoto.stub(:new) { mock_host_family_photo(:save => true) }
        post :create, :host_family_photo => {}
        response.should redirect_to(host_family_photo_url(mock_host_family_photo))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved host_family_photo as @host_family_photo" do
        HostFamilyPhoto.stub(:new).with({'these' => 'params'}) { mock_host_family_photo(:save => false) }
        post :create, :host_family_photo => {'these' => 'params'}
        assigns(:host_family_photo).should be(mock_host_family_photo)
      end

      it "re-renders the 'new' template" do
        HostFamilyPhoto.stub(:new) { mock_host_family_photo(:save => false) }
        post :create, :host_family_photo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested host_family_photo" do
        HostFamilyPhoto.stub(:find).with("37") { mock_host_family_photo }
        mock_host_family_photo.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :host_family_photo => {'these' => 'params'}
      end

      it "assigns the requested host_family_photo as @host_family_photo" do
        HostFamilyPhoto.stub(:find) { mock_host_family_photo(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:host_family_photo).should be(mock_host_family_photo)
      end

      it "redirects to the host_family_photo" do
        HostFamilyPhoto.stub(:find) { mock_host_family_photo(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(host_family_photo_url(mock_host_family_photo))
      end
    end

    describe "with invalid params" do
      it "assigns the host_family_photo as @host_family_photo" do
        HostFamilyPhoto.stub(:find) { mock_host_family_photo(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:host_family_photo).should be(mock_host_family_photo)
      end

      it "re-renders the 'edit' template" do
        HostFamilyPhoto.stub(:find) { mock_host_family_photo(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested host_family_photo" do
      HostFamilyPhoto.stub(:find).with("37") { mock_host_family_photo }
      mock_host_family_photo.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the host_family_photos list" do
      HostFamilyPhoto.stub(:find) { mock_host_family_photo }
      delete :destroy, :id => "1"
      response.should redirect_to(host_family_photos_url)
    end
  end

end
