require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NewsUpdatesController do

  def mock_news_update(stubs={})
    @mock_news_update ||= mock_model(NewsUpdate, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all news_updates as @news_updates" do
      NewsUpdate.stub(:all) { [mock_news_update] }
      get :index
      assigns(:news_updates).should eq([mock_news_update])
    end
  end

  describe "GET show" do
    it "assigns the requested news_update as @news_update" do
      NewsUpdate.stub(:find).with("37") { mock_news_update }
      get :show, :id => "37"
      assigns(:news_update).should be(mock_news_update)
    end
  end

  describe "GET new" do
    it "assigns a new news_update as @news_update" do
      NewsUpdate.stub(:new) { mock_news_update }
      get :new
      assigns(:news_update).should be(mock_news_update)
    end
  end

  describe "GET edit" do
    it "assigns the requested news_update as @news_update" do
      NewsUpdate.stub(:find).with("37") { mock_news_update }
      get :edit, :id => "37"
      assigns(:news_update).should be(mock_news_update)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created news_update as @news_update" do
        NewsUpdate.stub(:new).with({'these' => 'params'}) { mock_news_update(:save => true) }
        post :create, :news_update => {'these' => 'params'}
        assigns(:news_update).should be(mock_news_update)
      end

      it "redirects to the created news_update" do
        NewsUpdate.stub(:new) { mock_news_update(:save => true) }
        post :create, :news_update => {}
        response.should redirect_to(news_update_url(mock_news_update))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved news_update as @news_update" do
        NewsUpdate.stub(:new).with({'these' => 'params'}) { mock_news_update(:save => false) }
        post :create, :news_update => {'these' => 'params'}
        assigns(:news_update).should be(mock_news_update)
      end

      it "re-renders the 'new' template" do
        NewsUpdate.stub(:new) { mock_news_update(:save => false) }
        post :create, :news_update => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested news_update" do
        NewsUpdate.stub(:find).with("37") { mock_news_update }
        mock_news_update.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :news_update => {'these' => 'params'}
      end

      it "assigns the requested news_update as @news_update" do
        NewsUpdate.stub(:find) { mock_news_update(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:news_update).should be(mock_news_update)
      end

      it "redirects to the news_update" do
        NewsUpdate.stub(:find) { mock_news_update(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(news_update_url(mock_news_update))
      end
    end

    describe "with invalid params" do
      it "assigns the news_update as @news_update" do
        NewsUpdate.stub(:find) { mock_news_update(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:news_update).should be(mock_news_update)
      end

      it "re-renders the 'edit' template" do
        NewsUpdate.stub(:find) { mock_news_update(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested news_update" do
      NewsUpdate.stub(:find).with("37") { mock_news_update }
      mock_news_update.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the news_updates list" do
      NewsUpdate.stub(:find) { mock_news_update }
      delete :destroy, :id => "1"
      response.should redirect_to(news_updates_url)
    end
  end

end
