require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ServiceGradesController do

  def mock_service_grade(stubs={})
    @mock_service_grade ||= mock_model(ServiceGrade, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all service_grades as @service_grades" do
      ServiceGrade.stub(:all) { [mock_service_grade] }
      get :index
      assigns(:service_grades).should eq([mock_service_grade])
    end
  end

  describe "GET show" do
    it "assigns the requested service_grade as @service_grade" do
      ServiceGrade.stub(:find).with("37") { mock_service_grade }
      get :show, :id => "37"
      assigns(:service_grade).should be(mock_service_grade)
    end
  end

  describe "GET new" do
    it "assigns a new service_grade as @service_grade" do
      ServiceGrade.stub(:new) { mock_service_grade }
      get :new
      assigns(:service_grade).should be(mock_service_grade)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_grade as @service_grade" do
      ServiceGrade.stub(:find).with("37") { mock_service_grade }
      get :edit, :id => "37"
      assigns(:service_grade).should be(mock_service_grade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created service_grade as @service_grade" do
        ServiceGrade.stub(:new).with({'these' => 'params'}) { mock_service_grade(:save => true) }
        post :create, :service_grade => {'these' => 'params'}
        assigns(:service_grade).should be(mock_service_grade)
      end

      it "redirects to the created service_grade" do
        ServiceGrade.stub(:new) { mock_service_grade(:save => true) }
        post :create, :service_grade => {}
        response.should redirect_to(service_grade_url(mock_service_grade))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_grade as @service_grade" do
        ServiceGrade.stub(:new).with({'these' => 'params'}) { mock_service_grade(:save => false) }
        post :create, :service_grade => {'these' => 'params'}
        assigns(:service_grade).should be(mock_service_grade)
      end

      it "re-renders the 'new' template" do
        ServiceGrade.stub(:new) { mock_service_grade(:save => false) }
        post :create, :service_grade => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_grade" do
        ServiceGrade.stub(:find).with("37") { mock_service_grade }
        mock_service_grade.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :service_grade => {'these' => 'params'}
      end

      it "assigns the requested service_grade as @service_grade" do
        ServiceGrade.stub(:find) { mock_service_grade(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:service_grade).should be(mock_service_grade)
      end

      it "redirects to the service_grade" do
        ServiceGrade.stub(:find) { mock_service_grade(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(service_grade_url(mock_service_grade))
      end
    end

    describe "with invalid params" do
      it "assigns the service_grade as @service_grade" do
        ServiceGrade.stub(:find) { mock_service_grade(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:service_grade).should be(mock_service_grade)
      end

      it "re-renders the 'edit' template" do
        ServiceGrade.stub(:find) { mock_service_grade(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_grade" do
      ServiceGrade.stub(:find).with("37") { mock_service_grade }
      mock_service_grade.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the service_grades list" do
      ServiceGrade.stub(:find) { mock_service_grade }
      delete :destroy, :id => "1"
      response.should redirect_to(service_grades_url)
    end
  end

end
