require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StudentHostfamilyPicturesController do

  def mock_student_hostfamily_picture(stubs={})
    @mock_student_hostfamily_picture ||= mock_model(StudentHostfamilyPicture, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all student_hostfamily_pictures as @student_hostfamily_pictures" do
      StudentHostfamilyPicture.stub(:all) { [mock_student_hostfamily_picture] }
      get :index
      assigns(:student_hostfamily_pictures).should eq([mock_student_hostfamily_picture])
    end
  end

  describe "GET show" do
    it "assigns the requested student_hostfamily_picture as @student_hostfamily_picture" do
      StudentHostfamilyPicture.stub(:find).with("37") { mock_student_hostfamily_picture }
      get :show, :id => "37"
      assigns(:student_hostfamily_picture).should be(mock_student_hostfamily_picture)
    end
  end

  describe "GET new" do
    it "assigns a new student_hostfamily_picture as @student_hostfamily_picture" do
      StudentHostfamilyPicture.stub(:new) { mock_student_hostfamily_picture }
      get :new
      assigns(:student_hostfamily_picture).should be(mock_student_hostfamily_picture)
    end
  end

  describe "GET edit" do
    it "assigns the requested student_hostfamily_picture as @student_hostfamily_picture" do
      StudentHostfamilyPicture.stub(:find).with("37") { mock_student_hostfamily_picture }
      get :edit, :id => "37"
      assigns(:student_hostfamily_picture).should be(mock_student_hostfamily_picture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created student_hostfamily_picture as @student_hostfamily_picture" do
        StudentHostfamilyPicture.stub(:new).with({'these' => 'params'}) { mock_student_hostfamily_picture(:save => true) }
        post :create, :student_hostfamily_picture => {'these' => 'params'}
        assigns(:student_hostfamily_picture).should be(mock_student_hostfamily_picture)
      end

      it "redirects to the created student_hostfamily_picture" do
        StudentHostfamilyPicture.stub(:new) { mock_student_hostfamily_picture(:save => true) }
        post :create, :student_hostfamily_picture => {}
        response.should redirect_to(student_hostfamily_picture_url(mock_student_hostfamily_picture))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved student_hostfamily_picture as @student_hostfamily_picture" do
        StudentHostfamilyPicture.stub(:new).with({'these' => 'params'}) { mock_student_hostfamily_picture(:save => false) }
        post :create, :student_hostfamily_picture => {'these' => 'params'}
        assigns(:student_hostfamily_picture).should be(mock_student_hostfamily_picture)
      end

      it "re-renders the 'new' template" do
        StudentHostfamilyPicture.stub(:new) { mock_student_hostfamily_picture(:save => false) }
        post :create, :student_hostfamily_picture => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested student_hostfamily_picture" do
        StudentHostfamilyPicture.stub(:find).with("37") { mock_student_hostfamily_picture }
        mock_student_hostfamily_picture.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :student_hostfamily_picture => {'these' => 'params'}
      end

      it "assigns the requested student_hostfamily_picture as @student_hostfamily_picture" do
        StudentHostfamilyPicture.stub(:find) { mock_student_hostfamily_picture(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:student_hostfamily_picture).should be(mock_student_hostfamily_picture)
      end

      it "redirects to the student_hostfamily_picture" do
        StudentHostfamilyPicture.stub(:find) { mock_student_hostfamily_picture(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(student_hostfamily_picture_url(mock_student_hostfamily_picture))
      end
    end

    describe "with invalid params" do
      it "assigns the student_hostfamily_picture as @student_hostfamily_picture" do
        StudentHostfamilyPicture.stub(:find) { mock_student_hostfamily_picture(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:student_hostfamily_picture).should be(mock_student_hostfamily_picture)
      end

      it "re-renders the 'edit' template" do
        StudentHostfamilyPicture.stub(:find) { mock_student_hostfamily_picture(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested student_hostfamily_picture" do
      StudentHostfamilyPicture.stub(:find).with("37") { mock_student_hostfamily_picture }
      mock_student_hostfamily_picture.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the student_hostfamily_pictures list" do
      StudentHostfamilyPicture.stub(:find) { mock_student_hostfamily_picture }
      delete :destroy, :id => "1"
      response.should redirect_to(student_hostfamily_pictures_url)
    end
  end

end
