require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SuccessCasesController do

  def mock_success_case(stubs={})
    @mock_success_case ||= mock_model(SuccessCase, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all success_cases as @success_cases" do
      SuccessCase.stub(:all) { [mock_success_case] }
      get :index
      assigns(:success_cases).should eq([mock_success_case])
    end
  end

  describe "GET show" do
    it "assigns the requested success_case as @success_case" do
      SuccessCase.stub(:find).with("37") { mock_success_case }
      get :show, :id => "37"
      assigns(:success_case).should be(mock_success_case)
    end
  end

  describe "GET new" do
    it "assigns a new success_case as @success_case" do
      SuccessCase.stub(:new) { mock_success_case }
      get :new
      assigns(:success_case).should be(mock_success_case)
    end
  end

  describe "GET edit" do
    it "assigns the requested success_case as @success_case" do
      SuccessCase.stub(:find).with("37") { mock_success_case }
      get :edit, :id => "37"
      assigns(:success_case).should be(mock_success_case)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created success_case as @success_case" do
        SuccessCase.stub(:new).with({'these' => 'params'}) { mock_success_case(:save => true) }
        post :create, :success_case => {'these' => 'params'}
        assigns(:success_case).should be(mock_success_case)
      end

      it "redirects to the created success_case" do
        SuccessCase.stub(:new) { mock_success_case(:save => true) }
        post :create, :success_case => {}
        response.should redirect_to(success_case_url(mock_success_case))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved success_case as @success_case" do
        SuccessCase.stub(:new).with({'these' => 'params'}) { mock_success_case(:save => false) }
        post :create, :success_case => {'these' => 'params'}
        assigns(:success_case).should be(mock_success_case)
      end

      it "re-renders the 'new' template" do
        SuccessCase.stub(:new) { mock_success_case(:save => false) }
        post :create, :success_case => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested success_case" do
        SuccessCase.stub(:find).with("37") { mock_success_case }
        mock_success_case.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :success_case => {'these' => 'params'}
      end

      it "assigns the requested success_case as @success_case" do
        SuccessCase.stub(:find) { mock_success_case(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:success_case).should be(mock_success_case)
      end

      it "redirects to the success_case" do
        SuccessCase.stub(:find) { mock_success_case(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(success_case_url(mock_success_case))
      end
    end

    describe "with invalid params" do
      it "assigns the success_case as @success_case" do
        SuccessCase.stub(:find) { mock_success_case(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:success_case).should be(mock_success_case)
      end

      it "re-renders the 'edit' template" do
        SuccessCase.stub(:find) { mock_success_case(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested success_case" do
      SuccessCase.stub(:find).with("37") { mock_success_case }
      mock_success_case.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the success_cases list" do
      SuccessCase.stub(:find) { mock_success_case }
      delete :destroy, :id => "1"
      response.should redirect_to(success_cases_url)
    end
  end

end
